name: mirros-one
version: "0.1.0"
summary: Just a test
description: Testing snap containers for mirr.OS one.
grade: stable
confinement: strict

apps:
  join-network:
    command: sh $SNAP/opt/join-network/bin/cmd.sh
    plugs: [network-manager]
  
parts:
  cmd:
    source: .
    plugin: dump
    organize:
      cmd.sh: opt/join-network/bin/cmd.sh
  nmcli:
    plugin: nil
    stage-packages:
      - network-manager
    organize:
      usr/bin/nmcli: bin/nmcli
