#!/bin/sh -e

# Run any commands needed to setup the snap.
# This could be downloading a list of dynamic configuration options or creating a database.

# nginx setup
envsubst < $SNAP/nginx.conf > $SNAP_DATA/nginx.conf
mkdir $SNAP_DATA/nginx

# Rails app setup
cd $SNAP/api

# Generates an individual secret for each snap installation. Environment variables set here might not be present at all times across revisions, so we store it in a file. TODO: Check if we can leverage snap configuration.
$SNAP/bin/rails secret > $SNAP_DATA/secret

# Set up the API database.
SECRET_KEY_BASE=$(cat $SNAP_DATA/secret) RAILS_ENV=production $SNAP/bin/rails db:create db:migrate db:seed
