#!/bin/sh -e
# cat $SNAP/nginx.conf | envsubst '${SNAP_NAME} ${SNAP_COMMON}' > $SNAP_COMMON/nginx.conf

# FIXME: Remove once https://github.com/snapcore/snapd/pull/5777 is in stable
#snapctl stop --disable mirros-one.dns

# Copy new migrations and gems from read-only location to writable mount
cp -rn "$SNAP"/api/vendor_installed/* "$SNAP_DATA"/rails/vendor
cp -rn "$SNAP"/api/db_installed/* "$SNAP_DATA"/rails/db

cd "$SNAP"/api # required for bundler to find the gemfile
export SECRET_KEY_BASE=$(cat "$SNAP_DATA"/secret) 
export RAILS_ENV=production
"$SNAP"/wrapper "$SNAP"/api/bin/rails db:migrate
